config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'top_pages/index'
  get '/subscriptions', to: 'subscriptions#index'
  get '/orders', to: 'orders#index'
  get '/users', to: 'users#index'
  get '/posts', to: 'posts#index'
  get '/add_stores', to: 'add_stores#index'
  get '/datas', to: 'data#index'
  get '/buttons', to: 'buttons#index'

  root 'top_pages#index'
  
  resources :tweets do
    resources :comments, only: :create
  end
  resources :users, only: :show
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :tweet  # tweetsテーブルとのアソシエーション
  belongs_to :user  # usersテーブルとのアソシエーション
end

app/models/order.rb
class Order < ApplicationRecord
  # モデルの定義
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :text, presence: true
  belongs_to :user
  has_many :comments  # commentsテーブルとのアソシエーション
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets
  has_many :comments  # commentsテーブルとのアソシエーション
end

app/controllers/buttons_controller.rb
class ButtonsController < ApplicationController
  def perform_action
    # ボタンがクリックされたときに実行する処理を記述
  end
end

app/controllers/data_controller.rb
class DataController < ApplicationController
  def index
  end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def index
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    render "orders/index"
  end

  def assets
    path = params[:path]
    send_file Rails.root.join('app/assets/images', path)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end
end

app/controllers/top_pages_controller.rb
class TopPagesController < ApplicationController
  def index
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:edit, :show]
  before_action :move_to_index, except: [:index, :show]


  def index
    @tweets = Tweet.includes(:user).order("created_at DESC")
  end

  def new
    @tweet = Tweet.new
  end

  def create
    Tweet.create(tweet_params)
    redirect_to '/'
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    redirect_to root_path
  end

  def edit
  end

  def update
    tweet = Tweet.find(params[:id])
    tweet.update(tweet_params)
    redirect_to root_path
  end

  def show
  end
  
  private
  def tweet_params
    params.require(:tweet).permit(:image, :text).merge(user_id: current_user.id)
  end

  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

    def index
      
    end
  
    def show
      user = User.find(params[:id])
      @nickname = user.nickname
      @tweets = user.tweets
    end
  
    def new
      @user = User.new
    end
  
    def create
      @user = User.new(user_params)
      if @user.save
        redirect_to @user
      else
        render 'new'
      end
    end
  
    private

  def user_params
    params.require(:user).permit(:nick_name, :first_name, :last_name)
  end
end

app/helpers/add_stores_helper.rb
module AddStoresHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buttons_helper.rb
module ButtonsHelper
end

app/helpers/data_helper.rb
module DataHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/top_pages_helper.rb
module TopPagesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/orders/index.html.erb
<ol class="list-group list-group-numbered">
  <li class="list-group-item d-flex justify-content-between align-items-start">
    <div class="ms-2 me-auto">
      <div class="fw-bold">注文情報</div>
      注文内容
    </div>
    <span class="badge bg-primary rounded-pill"></span>
  </li>
  <li class="list-group-item d-flex justify-content-between align-items-start">
    <div class="ms-2 me-auto">
      <div class="fw-bold">店舗</div>
      店舗情報
    </div>
    <span class="badge bg-primary rounded-pill"></span>
  </li>
  <li class="list-group-item d-flex justify-content-between align-items-start">
    <div class="ms-2 me-auto">
      <div class="fw-bold">メニュー</div>
      メニュー内容
    </div>
    <span class="badge bg-primary rounded-pill"></span>
  </li>
</ol>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %>
      <%= form.text_field :image, placeholder: "Image Url" %>
      <%= form.text_area :text, placeholder: "text", rows: "10" %>
      <%= form.submit "SEND" %>
    <% end %>

app/views/tweets/_tweet.html.erb
<div class="content_post" style="background-image: url(<%= tweet.image %>);">
      <div class="more">
        <span><%= image_tag 'arrow_top.png' %></span>
        <ul class="more_list">
          <li>
            <%= link_to '詳細', tweet_path(tweet.id) %>
          </li>
          <% if user_signed_in? && current_user.id == tweet.user_id %>
            <li>
              <%= link_to '編集', edit_tweet_path(tweet.id) %>
            </li>
            <li>
              <%= link_to '削除', tweet_path(tweet.id), data: { turbo_method: :delete } %>
            </li>
          <% end %>
        </ul>
      </div>
      <p><%= tweet.text %></p>
      <span class="name">
        <a href="/users/<%= tweet.user.id %>">
          <span>投稿者</span><%= tweet.user.nickname %>
        </a>
      </span>
    </div>

app/views/tweets/edit.html.erb
<div class="contents row">
  <div class="container">
    <h3>編集する</h3>
    <%= render partial: "form", locals: { tweet: @tweet } %>
  </div>
</div>

app/views/tweets/index.html.erb
<div class="contents row">
  <% @tweets.each do |tweet| %>
  <%= render partial: "tweet", locals: { tweet: tweet } %>
  <% end %>
</div>

app/views/tweets/new.html.erb
<div class="contents row">
  <div class="container">
    <h3>投稿する</h3>
    <%= render partial: "form", locals: { tweet: @tweet } %>
  </div>
</div>

app/views/tweets/show.html.erb
<div class="contents row">
  <div class="content_post" style="background-image: url(<%= @tweet.image %>);">
  <% if user_signed_in? && current_user.id == @tweet.user_id %>
    <div class="more">
      <span><%= image_tag 'arrow_top.png' %></span>
      <ul class="more_list">
        <li>
          <%= link_to '編集', edit_tweet_path(@tweet.id) %>
        </li>
        <li>
          <%= link_to '削除', tweet_path(@tweet.id), data: { turbo_method: :delete } %>
        </li>
      </ul>
    </div>
    <% end %>
    <p><%= @tweet.text %></p>
    <span class="name">
      <a href="/users/<%= @tweet.user.id %>">
        <span>投稿者</span><%= @tweet.user.nickname %>
      </a>
    </span>
  </div>
</div>