config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'top_pages/index'
  get '/subscriptions', to: 'subscriptions#index'
  get '/orders', to: 'orders#index'
  get '/users', to: 'users#index'
  get '/posts', to: 'posts#index'
  get '/add_stores', to: 'add_stores#index'
  get '/datas', to: 'data#index'
  get '/buttons', to: 'buttons#index'

  root 'top_pages#index'
  
  resources :tweets do
    resources :comments, only: :create
  end
  resources :users, only: :show
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :tweet  # tweetsテーブルとのアソシエーション
  belongs_to :user  # usersテーブルとのアソシエーション
end

app/models/order.rb
class Order < ApplicationRecord
  # モデルの定義
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :text, presence: true
  belongs_to :user
  has_many :comments  # commentsテーブルとのアソシエーション
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets
  has_many :comments  # commentsテーブルとのアソシエーション
end

app/controllers/data_controller.rb
class DataController < ApplicationController
  def index
  end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def index
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    render "orders/index"
  end

  def assets
    path = params[:path]
    send_file Rails.root.join('app/assets/images', path)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

    def index
      
    end
  
    def show
      user = User.find(params[:id])
      @nickname = user.nickname
      @tweets = user.tweets
    end
  
    def new
      @user = User.new
    end
  
    def create
      @user = User.new(user_params)
      if @user.save
        redirect_to @user
      else
        render 'new'
      end
    end
  
    private

  def user_params
    params.require(:user).permit(:nick_name, :first_name, :last_name)
  end
end

app/helpers/add_stores_helper.rb
module AddStoresHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buttons_helper.rb
module ButtonsHelper
end

app/helpers/data_helper.rb
module DataHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/top_pages_helper.rb
module TopPagesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Every</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <header class="header">
      <div class="header__bar row">
        <h1 class="grid-6"><a href="/tweets">みんなの投稿</a></h1>

        <% if user_signed_in? %>
          <div class="user_nav grid-6">
          <span><%= current_user.nickname %>
            <ul class="user__info">
              <li>
                <%= link_to "マイページ", "/users/#{current_user.id}" %>
                <%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete } %>
              </li>
            </ul>
          </span>
          <%= link_to "投稿する", new_tweet_path, class: "post" %>
        </div>
    <% else %>
      <div class="grid-6">
        <%= link_to "ログイン", new_user_session_path, class: "post" %>
        <%= link_to "新規登録", new_user_registration_path, class: "post" %>
      </div>
    <% end %>
        
        <div class="user_nav grid-6">
          <%# <a class="post" href="/tweets/new">投稿する</a> %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer>
      <p>
        
      </p>
    </footer>
  </body>
</html>